services:
  - type: web
    name: caption-changer-bot
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: BOT_TOKEN
        sync: false
      - key: FORCE_SUB_CHANNEL
        sync: false
